### ISSUE TITLE
conda install -c bioconda bioconductor-genomeinfodbdata=1.2.9

### ISSUE THREAD

**Issue by yhw320** [Bioconductor/GenomeInfoDbData#6]
I would like to install genomeinfodbdata (version:1.2.9) using Conda. But it took all day to report the error.
The command and error information are as follows.  Looking forward to your reply!

conda install -c bioconda bioconductor-genomeinfodbdata=1.2.9

ERROR conda.core.link: execute945): an error occurred while installing package bioconda::bioconductor-genomeinfodbdata-1.2.9-r42hdfd78ao'

**Comment by z5ouyang** [comment]
Same error!
All previous versions are removed? the following link is not working anymore (which is set in conda '...post-link.sh'):
https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz

**Comment by LiNk-NY** [comment]
@z5ouyang 
FWIW that link works for me. Please check that you are not behind a firewall or have limited internet access.
@yhw320 
Unfortunately, we do not manage or endorse conda installations for Bioconductor packages. The framework is error prone. 

Best,
Marcel

**Comment by z5ouyang** [comment]
The link was NOT working for two weeks (Thus you could not install through BiocManager either). It was just fix over the past weekends. You can contact the bioconductor team to confirm.

**Comment by LiNk-NY** [comment]
Sorry for the inconvenience. We will do a better job of keeping the old package links stable. 
We recommend that you always use the latest version of R and Bioconductor, if possible.
