### ISSUE TITLE
Problem installing GenomeInfoDbData

### ISSUE THREAD

**Issue by Anaherasm** [Bioconductor/GenomeInfoDbData#7]
Hello,

I am writing here because it is impossible to me to install GenomeInfoDbData and I don't understand why. I am currently using R 4.3.1. 

Here is the message I obtained when I tried to install it: 

_> BiocManager::install("GenomeInfoDbData")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing package(s) 'BiocVersion', 'GenomeInfoDbData'
probando la URL 'https://bioconductor.org/packages/3.17/bioc/bin/windows/contrib/4.3/BiocVersion_3.17.1.zip'
Content type 'application/zip' length 8264 bytes
downloaded 8264 bytes

package ‘BiocVersion’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ana\AppData\Local\Temp\RtmpGW9aBl\downloaded_packages
installing the source package ‘GenomeInfoDbData’

probando la URL 'https://bioconductor.org/packages/3.17/data/annotation/src/contrib/GenomeInfoDbData_1.2.10.tar.gz'
Content type 'application/x-gzip' length 12026674 bytes (11.5 MB)
downloaded 11.5 MB

Error in setwd(exdir) : no es posible cambiar el directorio de trabajo

The downloaded source packages are in
	‘C:\Users\Ana\AppData\Local\Temp\RtmpGW9aBl\downloaded_packages’
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.3.1/library
  packages:
    foreign, KernSmooth, lattice, Matrix, mgcv, nlme, spatial, survival
Old packages: 'fansi', 'htmltools', 'testthat'
Update all/some/none? [a/s/n]: 
a

  There is a binary version available but the source version is later:
      binary source needs_compilation
fansi  1.0.4  1.0.5              TRUE

probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fansi_1.0.4.zip'
Content type 'application/zip' length 312864 bytes (305 KB)
downloaded 305 KB

probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/htmltools_0.5.6.1.zip'
Content type 'application/zip' length 355637 bytes (347 KB)
downloaded 347 KB

probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/testthat_3.2.0.zip'
Content type 'application/zip' length 2219811 bytes (2.1 MB)
downloaded 2.1 MB

package ‘fansi’ successfully unpacked and MD5 sums checked
package ‘htmltools’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘htmltools’
Warning: restored ‘htmltools’
package ‘testthat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ana\AppData\Local\Temp\RtmpGW9aBl\downloaded_packages
Warning messages:
1: In install.packages(...) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problema al copiar C:\Users\Ana\AppData\Local\R\win-library\4.3\00LOCK\htmltools\libs\x64\htmltools.dll  a C:\Users\Ana\AppData\Local\R\win-library\4.3\htmltools\libs\x64\htmltools.dll: Permission denied_

I would be very grateful if anyone could help me solve this problem

**Comment by hpages** [comment]
Your local setup seems to be problematic. Can you install any CRAN package at all? For example, can you start a new R session, try to install **matrixStats** and **ggplot2**, with `install.packages(c("matrixStats", "ggplot2"))`, and report here how it went? Also please show the output of `BiocManager::valid()` and your `sessionInfo()`? Thanks

**Comment by Anaherasm** [comment]
Thank you for your help. I could easily install both matrixStats and ggplot, but the problems with GenomeInfoDbData persist. Here is the outcome:
R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

``R es un software libre y viene sin GARANTIA ALGUNA.
Usted puede redistribuirlo bajo ciertas circunstancias.
Escriba 'license()' o 'licence()' para detalles de distribucion.

R es un proyecto colaborativo con muchos contribuyentes.
Escriba 'contributors()' para obtener más información y
'citation()' para saber cómo citar R o paquetes de R en publicaciones.

Escriba 'demo()' para demostraciones, 'help()' para el sistema on-line de ayuda,
o 'help.start()' para abrir el sistema de ayuda HTML con su navegador.
Escriba 'q()' para salir de R.

Error in setwd(dir) : no es posible cambiar el directorio de trabajo
> install.packages(c("matrixStats", "ggplot2"))
Installing packages into ‘C:/Users/Ana/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/matrixStats_1.0.0.zip'
Content type 'application/zip' length 531753 bytes (519 KB)
downloaded 519 KB

probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/ggplot2_3.4.3.zip'
Content type 'application/zip' length 3329956 bytes (3.2 MB)
downloaded 3.2 MB

package ‘matrixStats’ successfully unpacked and MD5 sums checked
package ‘ggplot2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ana\AppData\Local\Temp\Rtmpy23boc\downloaded_packages
> BiocManager::install("GenomeInfoDbData")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")'
for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing package(s) 'GenomeInfoDbData'
installing the source package ‘GenomeInfoDbData’

probando la URL 'https://bioconductor.org/packages/3.17/data/annotation/src/contrib/GenomeInfoDbData_1.2.10.tar.gz'
Content type 'application/x-gzip' length 12026674 bytes (11.5 MB)
downloaded 11.5 MB

Error in setwd(exdir) : no es posible cambiar el directorio de trabajo

The downloaded source packages are in
	‘C:\Users\Ana\AppData\Local\Temp\Rtmpy23boc\downloaded_packages’
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.3.1/library
  packages:
    foreign, KernSmooth, lattice, Matrix, mgcv, nlme, rpart, spatial, survival
Warning message:
In install.packages(...) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status
> BiocManager::valid()
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")'
for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
[1] TRUE
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Spanish_Spain.utf8  LC_CTYPE=Spanish_Spain.utf8    LC_MONETARY=Spanish_Spain.utf8
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.utf8    

time zone: Europe/Madrid
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.22 zlibbioc_1.46.0     compiler_4.3.1      IRanges_2.34.1      XVector_0.40.0     
 [6] tools_4.3.1         RCurl_1.98-1.12     rstudioapi_0.15.0   crayon_1.5.2        S4Vectors_0.38.2   
[11] BiocGenerics_0.46.0 bitops_1.0-7        stats4_4.3.1       ``

**Comment by Anaherasm** [comment]
Is it possible that the issues are related to interactions with OneDrive? Because I am also having some troubles with programs like qiime2R

**Comment by hpages** [comment]
You're getting this error in a fresh R session, before doing anything else and before trying to install the **GenomeInfoDbData** package:
```
Error in setwd(dir) : no es posible cambiar el directorio de trabajo
```
This means that your R setup is broken, and it has nothing to do with **GenomeInfoDbData**.

Please seek help on the appropriate R mailing lists (maybe R-help) for how to properly set up R on your machine.

**Comment by Anaherasm** [comment]
Tahnk you for response. I would do so, because I am having issues in both, my personal and my laboratory computers.

**Comment by hpages** [comment]
good luck
