### ISSUE TITLE
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1

### ISSUE THREAD

**Issue by BoTang1** [Bioconductor/GenomeInfoDbData#8]
Hello,
  When I tried to use code:   "conda install bioconda::bioconductor-genomeinfodb". I got errors as showing in the following figure.
My R version: 4.3.3, 
conda version: 23.7.4
![2](https://github.com/user-attachments/assets/ad4570cb-6a31-4ec5-a155-8ca16dd577d3)

  Does anyone know anyway how to solve this problem? I searched many materials, and I still cannot solve it.

**Comment by lshep** [comment]
We don't control what bioconda provides.  I would reach out to them directly.  
For What Its Worth there are some posts  about it doing a quick google search as it seems to be a known issue to bioconda:
 
https://github.com/bioconda/bioconda-recipes/issues/28801
https://github.com/bioconda/bioconda-recipes/issues/13846

Some suggest you might have better luck with a manual install.
